
# This is a basic workflow to help you get started with the Run Jtest action.
name: Windows action
on:
  # Trigger the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build-on-windows:
    name: Analyze project with Jtest
    
    permissions:
      # required for all workflows
      security-events: write
      
    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v3
 #     with:
   #     ref: fix-crlf-issue
      
    # build the project.
    - name: build the batch file
      run: ./gradlew clean build
         
     # unzip the parasoft-report-transformer-1.0.0.zip.
    - name: unzip the parasoft-report-transformer-1.0.0.zip
      run: unzip build/distributions/parasoft-report-transformer-1.0.0.zip

    # Generates the jtest.data.json input file.
    - name: Create input for Jtest
      run: ./gradlew clean build jtest -I D:\Installed\Parasoft\parasoft_jtest_2024.1.1\jtest\integration\gradle\init.gradle "-Djtest.skip=true"

    # Runs code analysis with Jtest.
    - name: Run Jtest
      id: jtest
      uses: parasoft/run-jtest-action@2.0.0
      with:
        #Uses the jtest.data.json generated with the Gradle command in the previous step
        installDir: D:/Installed/Parasoft/parasoft_jtest_2024.1.1/jtest
        testConfig: 'jtest_settings.properties'
        input: build/jtest/jtest.data.json
        
    # converte the xml2sarif.
    - name: converte the xml2sarif
      run: parasoft-report-transformer-1.0.0\bin\XMLToSARIF.bat -i reports\report.xml -o reports\report-new.sarif
    
    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports/report-new.sarif # reports is a default location for reports directory

    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Static analysis reports
        path: reports/*.*
